image: docker:latest

stages:
  - build_images
  - customer_service

services:
  - name: docker:dind

service_discovery:
  stage: build_images
  rules:
    - when: manual
  script:
    - docker login -u $CI_REGISTRY_USER  -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
    - docker buildx create --use
    - docker buildx build --provenance false --platform linux/amd64,linux/arm64 -t gitlab-registry.ozon.dev/ygar/practice/service-discovery:latest --push ./src/Ozon.Route256.Practice.ServiceDiscovery

logistics_simulator:
  stage: build_images
  rules:
    - when: manual
  script:
    - docker login -u $CI_REGISTRY_USER  -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
    - docker buildx create --use
    - docker buildx build --provenance false --platform linux/amd64,linux/arm64 -t gitlab-registry.ozon.dev/ygar/practice/logistics-simulator:latest --push ./src/Ozon.Route256.Practice.LogisticsSimulator

orders_generator:
  stage: build_images
  rules:
    - when: manual
  script:
    - docker login -u $CI_REGISTRY_USER  -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
    - docker buildx create --use
    - docker buildx build --provenance false --platform linux/amd64,linux/arm64 -t gitlab-registry.ozon.dev/ygar/practice/orders-generator:latest --push ./src/Ozon.Route256.Practice.OrdersGenerator

build:
  stage: customer_service
  image: mcr.microsoft.com/dotnet/sdk:6.0
  needs: []
  script: 
    - dotnet restore src/Ozon.Route256.Practice.CustomerService/Ozon.Route256.Practice.CustomerService.csproj
    - dotnet build src/Ozon.Route256.Practice.CustomerService/Ozon.Route256.Practice.CustomerService.csproj --no-restore
       
test:
  stage: customer_service
  image: mcr.microsoft.com/dotnet/sdk:6.0
  needs: ["build"]
  script: 
    - dotnet restore src/Ozon.Route256.Practice.CustomerService/Ozon.Route256.Practice.CustomerService.csproj
    - dotnet build src/Ozon.Route256.Practice.CustomerService/Ozon.Route256.Practice.CustomerService.csproj --no-restore
